### ISSUE TITLE
lack estimate_params.mat

### ISSUE THREAD

**Issue by lcjlyj** [ikarib/FRBNY-IRIS#1]
when i run estimate_params.m ,matlab tells me lack of estimate_params.mat

**Comment by ikarib** [comment]
set reoptimize = 1

**Comment by lcjlyj** [comment]
Thanks for your answers to my last question! i have another question.

when I run the compare_model_and_data.m in FABNY-IRIS, matlab get an error
as following:
"Warning: Plot empty.
Error using svd
Input to SVD must not contain NaN or Inf.

Error in covfun.factorise (line 49)
[U,S] = svd(Ci);

Error in VAR/resample (line 158)
F = covfun.factorise(this.Omega);

Error in compare_model_and_data (line 97)
Y = resample(v,vdata,Inf,N,'wild=',true,'progress=',true);"

it looks like no data input.

how to input data in the program? which dataset should be input?

thanks

2017-04-29 4:31 GMT+08:00 Iskander Karibzhanov <notifications@github.com>:
