### ISSUE TITLE
when running compare_model_and_data.m   occurs error

### ISSUE THREAD

**Issue by lcjlyj** [ikarib/FRBNY-IRIS#2]
Thanks for your answers to my last question! i have another question.

when I run the compare_model_and_data.m in FABNY-IRIS, matlab get an error as following:
"Warning: Plot empty. 
Error using svd
Input to SVD must not contain NaN or Inf.

Error in covfun.factorise (line 49)
      [U,S] = svd(Ci);

Error in VAR/resample (line 158)
    F = covfun.factorise(this.Omega);

Error in compare_model_and_data (line 97)
Y = resample(v,vdata,Inf,N,'wild=',true,'progress=',true);"

it looks like  no data input.

how to input data in the program? which dataset should be input?

thanks

**Comment by ikarib** [comment]
changed this line:
```
ylist = get(mest,'yList'); %?ylist?
```
to exclude variables with missing data:
```
nfit = sum(~isnan(db2array(d,ylist)));
ylist = ylist(nfit>mean(nfit));
```
