### ISSUE TITLE
Error when running read_data.m

### ISSUE THREAD

**Issue by lnsongxf** [ikarib/FRBNY-IRIS#3]
Historical range

ans = 

    '1959Q3'    '2016Q4'

Connecting to the Haver Analytics database ...
Warning: Unable to open database. 
 
Warning: Will try FRED next. 
 
Connecting to the St. Louis Federal Reserve database (FRED) ...
FRED Database
	        GDP  .Title = ???
	    GDPCTPI  .Title = ???
	       PCEC  .Title = ???
	        FPI  .Title = ???
	   AWHNONAG  .Title = ???
	     CE16OV  .Title = ???
	    CNP16OV  .Title = ???
	    COMPNFB  .Title = ???
	      JCXFE  .Title = ???
	        DFF  .Title = ???
	        BAA  .Title = ???
	       GS10  .Title = ???
	THREEFYTP10  .Title = ???
	     USRECQ  .Title = ???
Misuse readtable (line 135)

**Comment by lnsongxf** [comment]
I typed read_data in the command window, and get follows:
"
Historical range

ans = 

    '1959Q3'    '2016Q4'

Connecting to the Haver Analytics database ...
Warning: Unable to open database. 
Warning: Will try FRED next. 
Connecting to the St. Louis Federal Reserve database (FRED) ...
FRED Database
	        GDP  .Title = ???
	    GDPCTPI  .Title = ???
	       PCEC  .Title = ???
	        FPI  .Title = ???
	   AWHNONAG  .Title = ???
	     CE16OV  .Title = ???
	    CNP16OV  .Title = ???
	    COMPNFB  .Title = ???
	      JCXFE  .Title = ???
	        DFF  .Title = ???
	        BAA  .Title = ???
	       GS10  .Title = ???
	THREEFYTP10  .Title = ???
	     USRECQ  .Title = ???
incorrect use of tseries (line 289)
IRIS Toolbox Error
*** Invalid size of comment array assigned to time series.


Error read_data (line 84)
F.INFCPI10YR = [tseries(dates,data.Combined); F.INFCPI10YR];

"

Whether it is because I can't acquire the data online to feed the code ?

Thanks for  your time, looking forward to your reply

**Comment by ikarib** [comment]
The problem is with datafeed toolbox. What matlab version do you use?

**Comment by lnsongxf** [comment]
I use matlab 2015b

**Comment by lnsongxf** [comment]
Because I am now in mainland China, it is common for us to experience outside internet connection problem, so I try the example in the document of datafeed toolbox, and I retreive the U.S. / Euro Foreign Exchange Rate from FRED successfully, so I can exclude the internet connection problem.

**Comment by ikarib** [comment]
I fixed this problem in IRIS-Solutions-Team/IRIS-Toolbox#70
